language: c
cache:
  - directories:
    - mpi
before_install:
  - bash ./config/build-mpi.sh
script:
  - export OMP_NUM_THREADS=1
  - export PATH=$(pwd)/mpi/bin:${PATH}
  - cp config/travis-mpicc.mk ./config.mk
  - make
  - make unit
