#! /bin/bash

mpicc -c -I. -I../../../../p3dfft/include/ decomp.c 
mpicc -c svn.c
mpicc -c pe.c
mpicc -c coords.c
mpicc -o test svn.o pe.o coords.o decomp.o ../../../../p3dfft/lib/libp3dfft.a ../../../../fftw/lib/libfftw3.a -pgf90libs

