#!/bin/bash --login

#PBS -N qscript
#PBS -l select=1:aoe=quad_100
#PBS -l walltime=00:20:00
#PBS -A k01-kevin

cd $PBS_O_WORKDIR
export KMP_AFFINITY=disabled
export OMP_NUM_THREADS=128

echo "OMP_NUM_THREADS ${OMP_NUM_THREADS}"

aprun -n 1 hostname
aprun -n 1 -d $OMP_NUM_THREADS -j 2 -cc depth ./Ludwig.exe

