#!/bin/bash
#PBS -l mppwidth=8
#PBS -l mppnppn=2
#PBS -l walltime=00:20:00
#PBS -A e73-oh

cd $PBS_O_WORKDIR
export NPROC=`qstat -f $PBS_JOBID | grep mppwidth | awk '{print $3}'`
export NTASK=`qstat -f $PBS_JOBID | grep mppnppn  | awk '{print $3}'`

aprun -n $NPROC -N $NTASK ./HLBLC08P > standard_out
