##############################################################################
#
#  Makefile
#
#  See individual model directories for specific targets
#
##############################################################################

clean:
	$(MAKE) -C d2q9 clean
	$(MAKE) -C d3q15 clean
	$(MAKE) -C d3q19 clean

test-clean:
	$(MAKE) clean
