name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and run the unit tests
        run: |
          cp config/coverage-gcc.mk config.mk
          make serial
          make
          make unit
          cd src
          gcov -abcfu *.c
      - name: Upload results
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
